---
- hosts: all
  become: true
  tasks:


  - name: install apache2/phps
    ansible.builtin.package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes






