---
- hosts: all
  become: true
  tasks:


  - name: install apache2/phps
    ansible.builtin.apt:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install httpd/php
    ansible.builtin.dnf:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
      use_backend: "dnf"
    when: ansible_distribution == "Fedora"





